# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               "Shailesh's Blog"
tagline:             'A simple place'
description:         'A simple place for some thoughts.'
url:                 https://kochhar.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shailesh Kochhar
  url:               https://twitter.com/60secondrun
  email:             shailesh.kochhar@gmail.com

# Custom vars
version:             1.0.0

nav_pages:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  
